all:
  favicon: favicon.ico
  title: Twitter | SHF
  meta:
    - charset="UTF-8"
    - http-equiv="X-UA-Compatible" content="IE=edge"
    - name="msapplication-TileColor" content="#ffffff"
    - name="msapplication-TileImage" content="img/favicon/ms-icon-144x144.png"
    - name="theme-color" content="#ffffff"
    
  link:
    - rel="apple-touch-icon" sizes="57x57" href=" img/favicon/apple-icon-57x57.png"
    - rel="apple-touch-icon" sizes="60x60" href="img/favicon/apple-icon-60x60.png"
    - rel="apple-touch-icon" sizes="72x72" href="img/favicon/apple-icon-72x72.png"
    - rel="apple-touch-icon" sizes="76x76" href="img/favicon/apple-icon-76x76.png"
    - rel="apple-touch-icon" sizes="114x114" href="img/favicon/apple-icon-114x114.png"
    - rel="apple-touch-icon" sizes="120x120" href="img/favicon/apple-icon-120x120.png"
    - rel="apple-touch-icon" sizes="144x144" href="img/favicon/apple-icon-144x144.png"
    - rel="apple-touch-icon" sizes="152x152" href="img/favicon/apple-icon-152x152.png"
    - rel="apple-touch-icon" sizes="180x180" href="img/favicon/apple-icon-180x180.png"
    - rel="icon" type="imageimg/favicon/png" sizes="192x192"  href="img/favicon/android-icon-192x192.png"
    - rel="icon" type="imageimg/favicon/png" sizes="32x32" href="img/favicon/favicon-32x32.png"
    - rel="icon" type="imageimg/favicon/png" sizes="96x96" href="img/favicon/favicon-96x96.png"
    - rel="icon" type="imageimg/favicon/png" sizes="16x16" href="img/favicon/favicon-16x16.png"
    - rel="manifest" href="img/favicon/manifest.json"
     
  stylesheet:
    - bootstrap.css
    - main.css
    - font-awesome.min.css  
    
  javascript:
    - jquery-1.11.3.min.js
    - bootstrap.js
    - main.js

shfSecurity:
  index:
    title: Login | SHF
    stylesheet:
      - signin.css

default:
  index:
    tittle: Twitter | SHF
    
    stylesheet:
      - default/default.css
    javascript:
      - index.js
           
